---
title: "plot calibrations"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)

Dsum <- data.frame()

tmp <- as.data.frame(df) %>% group_by(Individual, detR, ant, meth) %>%
  summarize(minD = min(distance, na.rm = T),
         maxD = max(distance, na.rm = T),
         medianD = median(distance, na.rm = T), 
         meanD = mean(distance, na.rm = T),
         NPos = n(),
         minD.m = min(distance.m, na.rm = T),
         maxD.m = max(distance.m, na.rm = T),
         medianD.m = median(distance.m, na.rm = T), 
         meanD.m = mean(distance.m, na.rm = T),
         NPos.m = sum(!is.na(distance.m)),
            .groups = "drop")
tmp$NAnt <- 1
tmp$NStat <- 1
tmp$SigTresh <- -90

Dsum <- rbind(Dsum, tmp)


tmp <- as.data.frame(df[df$Antenna.Count >= 2 & df$Station.Count >= 2,]) %>% 
  group_by(Individual, detR, ant, meth) %>%
  summarize(minD = min(distance, na.rm = T),
            maxD = max(distance, na.rm = T),
            medianD = median(distance, na.rm = T), 
            meanD = mean(distance, na.rm = T), 
            NPos = n(),
         minD.m = min(distance.m, na.rm = T),
         maxD.m = max(distance.m, na.rm = T),
         medianD.m = median(distance.m, na.rm = T), 
         meanD.m = mean(distance.m, na.rm = T),
         NPos.m = sum(!is.na(distance.m)),
         .groups = "drop")
tmp$NAnt <- 2
tmp$NStat <- 2
tmp$SigTresh <- -90

Dsum <- rbind(Dsum, tmp)

tmp <- as.data.frame(df[df$Antenna.Count >= 3 & df$Station.Count >= 2,]) %>% 
  group_by(Individual, detR, ant, meth) %>%
  summarize(minD = min(distance, na.rm = T),
            maxD = max(distance, na.rm = T),
            medianD = median(distance, na.rm = T), 
            meanD = mean(distance, na.rm = T), 
            NPos = n(),
         minD.m = min(distance.m, na.rm = T),
         maxD.m = max(distance.m, na.rm = T),
         medianD.m = median(distance.m, na.rm = T), 
         meanD.m = mean(distance.m, na.rm = T),
         NPos.m = sum(!is.na(distance.m)),
                     .groups = "drop")
tmp$NAnt <- 3
tmp$NStat <- 2
tmp$SigTresh <- -90

Dsum <- rbind(Dsum, tmp)

tmp <- as.data.frame(df[df$Signal.max >= -80,]) %>% 
  group_by(Individual, detR, ant, meth) %>%
  summarize(minD = min(distance, na.rm = T),
            maxD = max(distance, na.rm = T),
            medianD = median(distance, na.rm = T), 
            meanD = mean(distance, na.rm = T), 
            NPos = n(),
         minD.m = min(distance.m, na.rm = T),
         maxD.m = max(distance.m, na.rm = T),
         medianD.m = median(distance.m, na.rm = T), 
         meanD.m = mean(distance.m, na.rm = T),
         NPos.m = sum(!is.na(distance.m)),
                     .groups = "drop")
tmp$NAnt <- 1
tmp$NStat <- 1
tmp$SigTresh <- -80

Dsum <- rbind(Dsum, tmp)


tmp <- as.data.frame(df[df$Antenna.Count >= 2 & df$Station.Count >= 2 & df$Signal.max >= -80,]) %>% 
  group_by(Individual, detR, ant, meth) %>%
  summarize(minD = min(distance, na.rm = T),
            maxD = max(distance, na.rm = T),
            medianD = median(distance, na.rm = T), 
            meanD = mean(distance, na.rm = T), 
            NPos = n(),
         minD.m = min(distance.m, na.rm = T),
         maxD.m = max(distance.m, na.rm = T),
         medianD.m = median(distance.m, na.rm = T), 
         meanD.m = mean(distance.m, na.rm = T),
         NPos.m = sum(!is.na(distance.m)),
                     .groups = "drop")
tmp$NAnt <- 2
tmp$NStat <- 2
tmp$SigTresh <- -80

Dsum <- rbind(Dsum, tmp)

tmp <- as.data.frame(df[df$Antenna.Count >= 3 & df$Station.Count >= 2 & df$Signal.max >= -80,]) %>% 
  group_by(Individual, detR, ant, meth) %>%
  summarize(minD = min(distance, na.rm = T),
            maxD = max(distance, na.rm = T),
            medianD = median(distance, na.rm = T), 
            meanD = mean(distance, na.rm = T), 
            NPos = n(),
         minD.m = min(distance.m, na.rm = T),
         maxD.m = max(distance.m, na.rm = T),
         medianD.m = median(distance.m, na.rm = T), 
         meanD.m = mean(distance.m, na.rm = T),
         NPos.m = sum(!is.na(distance.m)),
                     .groups = "drop")
tmp$NAnt <- 3
tmp$NStat <- 2
tmp$SigTresh <- -80

Dsum <- rbind(Dsum, tmp)
```

```{r, fig.width=10, fig.height=4, warning = F, message = F}
## plot

for(t in unique(df$Individual)) {
  
  if(unique(df$Project[df$Individual == t]) == "maisC") ant <- "1-10"
  if(unique(df$Project[df$Individual == t]) == "maisD") ant <- "1-8"
  
  ggDetR <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1,]) + 
    stat_halfeye(aes(x = detR, y = distance, fill = ant, color = ant),
                 alpha = 0.3) +
    geom_text(aes(x = detR, y = 400, label = paste0(round(medianD, 2), " \n(", NPos, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == ant & Dsum$NAnt == 1 & Dsum$NStat == 1 & Dsum$SigTresh == -90,]) +
    geom_text(aes(x = detR, y = 600, label = paste0(round(medianD, 2), " \n(", NPos, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == "1-6" & Dsum$NAnt == 1 & Dsum$NStat == 1 & Dsum$SigTresh == -90,]) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("det. range") +
    ylab("distance error [m]") +
    
    scale_fill_viridis_d("Stations included", end = 0.9) +
    scale_color_viridis_d("Stations included", end = 0.9) +
  
    ggtitle(paste0(t, " - NStat 1, NAnt 1")) +
    theme_light(base_size = 0.8*bs)
  
  ggDetRm <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1,]) + 
    stat_halfeye(aes(x = detR, y = distance.m, fill = ant, color = ant),
                 alpha = 0.3) +
    geom_text(aes(x = detR, y = 400, label = paste0(round(medianD.m, 2), " \n(", NPos.m, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == ant & Dsum$NAnt == 1 & Dsum$NStat == 1 & Dsum$SigTresh == -90,]) +
    geom_text(aes(x = detR, y = 600, label = paste0(round(medianD.m, 2), " \n(", NPos.m, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == "1-6" & Dsum$NAnt == 1 & Dsum$NStat == 1 & Dsum$SigTresh == -90,]) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("det. range") +
    ylab("distance error [m]") +
    
    scale_fill_viridis_d("Stations included", end = 0.9) +
    scale_color_viridis_d("Stations included", end = 0.9) +
  
    ggtitle(paste0(t, " - NStat 1, NAnt 1 - rollMean")) +
    theme_light(base_size = 0.8*bs)
  
  
  ggDetR2 <- ggplot(df[df$Individual == t & df$Antenna.Count >= 2,]) + 
    stat_halfeye(aes(x = detR, y = distance, fill = ant, color = ant),
                 alpha = 0.3) +
    geom_text(aes(x = detR, y = 400, label = paste0(round(medianD, 2), " \n(", NPos, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == ant & Dsum$NAnt == 2 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    geom_text(aes(x = detR, y = 600, label = paste0(round(medianD, 2), " \n(", NPos, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == "1-6" & Dsum$NAnt == 2 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("det. range") +
    ylab("distance error [m]") +
    
    scale_fill_viridis_d("Stations included", end = 0.9) +
    scale_color_viridis_d("Stations included", end = 0.9) +
    
    ggtitle(paste0(t, " - NStat 2, NAnt 2")) +
    theme_light(base_size = 0.8*bs)
  
  ggDetR2m <- ggplot(df[df$Individual == t & df$Antenna.Count >= 2,]) + 
    stat_halfeye(aes(x = detR, y = distance.m, fill = ant, color = ant),
                 alpha = 0.3) +
    geom_text(aes(x = detR, y = 400, label = paste0(round(medianD.m, 2), " \n(", NPos.m, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == ant & Dsum$NAnt == 2 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    geom_text(aes(x = detR, y = 600, label = paste0(round(medianD.m, 2), " \n(", NPos.m, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == "1-6" & Dsum$NAnt == 2 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("det. range") +
    ylab("distance error [m]") +
    
    scale_fill_viridis_d("Stations included", end = 0.9) +
    scale_color_viridis_d("Stations included", end = 0.9) +
    
    ggtitle(paste0(t, " - NStat 2, NAnt 2 - rollMean")) +
    theme_light(base_size = 0.8*bs)
  
  
  ggDetR3 <- ggplot(df[df$Individual == t & df$Antenna.Count >= 3,]) + 
    stat_halfeye(aes(x = detR, y = distance, fill = ant, color = ant),
                 alpha = 0.3) +
    geom_text(aes(x = detR, y = 400, label = paste0(round(medianD, 2), " \n(", NPos, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == ant & Dsum$NAnt == 3 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    geom_text(aes(x = detR, y = 600, label = paste0(round(medianD, 2), " \n(", NPos, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == "1-6" & Dsum$NAnt == 3 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("det. range") +
    ylab("distance error [m]") +
    
    scale_fill_viridis_d("Stations included", end = 0.9) +
    scale_color_viridis_d("Stations included", end = 0.9) +
    
    ggtitle(paste0(t, " - NStat 2, NAnt 3")) +
    theme_light(base_size = 0.8*bs)
  
  ggDetR3m <- ggplot(df[df$Individual == t & df$Antenna.Count >= 3,]) + 
    stat_halfeye(aes(x = detR, y = distance.m, fill = ant, color = ant),
                 alpha = 0.3) +
    geom_text(aes(x = detR, y = 400, label = paste0(round(medianD.m, 2), " \n(", NPos.m, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == ant & Dsum$NAnt == 3 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    geom_text(aes(x = detR, y = 600, label = paste0(round(medianD.m, 2), " \n(", NPos.m, ")"), color = ant), 
              data = Dsum[Dsum$Individual == t & Dsum$ant == "1-6" & Dsum$NAnt == 3 & Dsum$NStat == 2 & Dsum$SigTresh == -90,]) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("det. range") +
    ylab("distance error [m]") +
    
    scale_fill_viridis_d("Stations included", end = 0.9) +
    scale_color_viridis_d("Stations included", end = 0.9) +
    
    ggtitle(paste0(t, " - NStat 2, NAnt 3 - rollMean")) +
    theme_light(base_size = 0.8*bs)
  
  ggNAnt <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    stat_halfeye(aes(x = Antenna.Count, y = distance),
               alpha = 0.3) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("Antenna Count") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NStat 1, Stat ", ant)) +
    theme_light(base_size = 0.8*bs)
  
  ggNAntm <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    stat_halfeye(aes(x = Antenna.Count, y = distance.m),
               alpha = 0.3) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("Antenna Count") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NStat 1, Stat ", ant, " - rollMean")) +
    theme_light(base_size = 0.8*bs)  
  
  ggNStat <- ggplot(df[df$Individual == t & df$Station.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    stat_halfeye(aes(x = Station.Count, y = distance),
                 alpha = 0.3) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("Station Count") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NAnt 1, Stat ", ant)) +
    theme_light(base_size = 0.8*bs)
  
  ggNStatm <- ggplot(df[df$Individual == t & df$Station.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    stat_halfeye(aes(x = Station.Count, y = distance.m),
                 alpha = 0.3) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("Station Count") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NAnt 1, Stat ", ant, " - rollMean")) +
    theme_light(base_size = 0.8*bs)  
  
  
  ggSigMax <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    geom_point(aes(x = Signal.max, y = distance),
               alpha = 0.3, pch = 1) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("max. Signal") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NAnt 1, NStat 1, Stat ", ant)) +
    theme_light(base_size = 0.8*bs)
  
  ggSigMaxm <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    geom_point(aes(x = Signal.max, y = distance.m),
               alpha = 0.3, pch = 1) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("max. Signal") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NAnt 1, NStat 1, Stat ", ant, " - rollMean")) +
    theme_light(base_size = 0.8*bs)  
  
  ggWeight <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    geom_point(aes(x = Weight, y = distance),
               alpha = 0.3, pch = 1) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("Weight") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NAnt 1, NStat 1, Stat ", ant)) +
    theme_light(base_size = 0.8*bs)
  
  ggWeightm <- ggplot(df[df$Individual == t & df$Antenna.Count >= 1 & df$detR %in% c("800m", "no") & df$ant ==  ant,]) + 
    geom_point(aes(x = Weight, y = distance.m),
               alpha = 0.3, pch = 1) +
    facet_wrap(~meth, scales = "free_x") +
    xlab("Weight") +
    ylab("distance error [m]") +
    ggtitle(paste0(t, " - detR 800m, NAnt 1, NStat 1, Stat ", ant, " - rollMean")) +
    theme_light(base_size = 0.8*bs)  
  
  
  print(ggDetR)
  print(ggDetRm)
  print(ggDetR2)
  print(ggDetR2m)
  print(ggDetR3)
  print(ggDetR3m)
  print(ggSigMax)
  print(ggSigMaxm)
  print(ggWeight)
  print(ggWeightm)
  print(ggNStat)
  print(ggNStatm)
  print(ggNAnt)
  print(ggNAntm)
  
}


```

